#!/usr/bin/env bash
# Add to crontab with all *s, (requires static IP config or DHCP address reservations)
if [[ "$(ping -W10 -c1 192.168.20.201 > /dev/null || ping -W10 -c1 192.168.20.204 > /dev/null && echo "online")" == "online" ]]; then
  date +%s > /tmp/last-seen
fi

if [[ $(expr "$(date +%s)" - "$(/bin/cat /tmp/last-seen)") -lt 600 ]]; then
  echo "home" > /tmp/home-status
else
  echo "away" > /tmp/home-status
fi
